# Generated by Django 3.0.9 on 2020-08-04 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='date of publication')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=35)),
                ('pub_date', models.DateField(verbose_name='date of publication')),
            ],
        ),
        migrations.CreateModel(
            name='TypicalJustificationItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateField(verbose_name='date of publication')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justification_items', to=settings.AUTH_USER_MODEL)),
                ('threats', models.ManyToManyField(to='threat_db.Justification')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatsDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('sources_of_threat', models.TextField()),
                ('objects_of_influence', models.TextField()),
                ('confidentiality_violation', models.BooleanField()),
                ('integrity_violation', models.BooleanField()),
                ('accessibility_violation', models.BooleanField()),
                ('pub_date', models.DateField(verbose_name='date of publication')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_descriptions', to='threat_db.Threat')),
            ],
        ),
        migrations.AddField(
            model_name='justification',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='threat_db.Threat'),
        ),
    ]
