# Generated by Django 3.0.9 on 2020-08-04 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threat_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('justification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='threat_db.Justification')),
            ],
        ),
    ]
